apiVersion: 1

datasources:
  - name: Music Warehouse
    uid: music-warehouse
    type: postgres
    access: proxy
    url: warehouse-db:5432
    user: $WAREHOUSE_USER
    secureJsonData:
      password: $WAREHOUSE_PASSWORD
    jsonData:
      database: $WAREHOUSE_DB
      sslmode: disable
      postgresVersion: 1800
      timescaledb: false
    isDefault: true
    editable: false
