CREATE TYPE "customer_status" AS ENUM (
  'active',
  'inactive',
  'blocked'
);

CREATE TYPE "artist_status" AS ENUM (
  'active',
  'inactive',
  'retired'
);

CREATE TYPE "album_type" AS ENUM (
  'album',
  'ep',
  'single',
  'compilation'
);

CREATE TYPE "album_artist_role" AS ENUM (
  'primary',
  'featured',
  'compilation'
);

CREATE TYPE "track_artist_role" AS ENUM (
  'primary',
  'featured',
  'composer',
  'performer',
  'producer'
);

CREATE TYPE "playlist_visibility" AS ENUM (
  'private',
  'public',
  'unlisted'
);

CREATE TYPE "order_status" AS ENUM (
  'pending',
  'confirmed',
  'completed',
  'cancelled',
  'refunded'
);

CREATE TYPE "payment_status" AS ENUM (
  'pending',
  'successful',
  'failed',
  'refunded'
);

CREATE TYPE "payment_mode" AS ENUM (
  'card',
  'upi',
  'net_banking',
  'wallet',
  'paypal'
);

CREATE TABLE "customer" (
  "customer_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "phone_no" varchar(30),
  "city" varchar(100),
  "country" varchar(100),
  "registration_date" date NOT NULL DEFAULT (current_date),
  "status" customer_status NOT NULL DEFAULT 'active',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "artist" (
  "artist_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "artist_name" varchar(255) NOT NULL,
  "biography" text,
  "website_url" varchar(500),
  "debut_year" smallint CHECK (debut_year >= 1800),
  "country" varchar(100),
  "status" artist_status NOT NULL DEFAULT 'active',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "album" (
  "album_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "album_title" varchar(255) NOT NULL,
  "release_date" date,
  "album_type" album_type NOT NULL,
  "album_price" decimal(10,2) NOT NULL CHECK (album_price >= 0) DEFAULT 0,
  "cover_image_url" varchar(500),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "album_artist" (
  "album_id" bigint NOT NULL,
  "artist_id" bigint NOT NULL,
  "artist_role" album_artist_role NOT NULL DEFAULT 'primary',
  PRIMARY KEY ("album_id", "artist_id")
);

CREATE TABLE "genre" (
  "genre_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "genre_name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "media_type" (
  "media_type_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "media_type_name" varchar(100) UNIQUE NOT NULL,
  "file_extension" varchar(20),
  "mime_type" varchar(100)
);

CREATE TABLE "track" (
  "track_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "album_id" bigint NOT NULL,
  "media_type_id" bigint NOT NULL,
  "track_name" varchar(255) NOT NULL,
  "composer" varchar(255),
  "duration_ms" integer NOT NULL CHECK (duration_ms > 0),
  "unit_price" decimal(10,2) NOT NULL CHECK (unit_price >= 0) DEFAULT 0,
  "is_explicit" boolean NOT NULL DEFAULT false,
  "track_number" smallint NOT NULL CHECK (track_number > 0),
  "disc_number" smallint NOT NULL CHECK (disc_number > 0) DEFAULT 1,
  "release_date" date,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "track_genre" (
  "track_id" bigint NOT NULL,
  "genre_id" bigint NOT NULL,
  PRIMARY KEY ("track_id", "genre_id")
);

CREATE TABLE "track_artist" (
  "track_id" bigint NOT NULL,
  "artist_id" bigint NOT NULL,
  "artist_role" track_artist_role NOT NULL DEFAULT 'primary',
  PRIMARY KEY ("track_id", "artist_id")
);

CREATE TABLE "playlist" (
  "playlist_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" bigint NOT NULL,
  "playlist_name" varchar(255) NOT NULL,
  "playlist_created_at" timestamp NOT NULL DEFAULT (now()),
  "playlist_visibility" playlist_visibility NOT NULL DEFAULT 'private',
  "description" text,
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "playlist_track" (
  "playlist_id" bigint NOT NULL,
  "track_id" bigint NOT NULL,
  "track_position" integer NOT NULL CHECK (track_position > 0),
  "added_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("playlist_id", "track_id")
);

CREATE TABLE "orders" (
  "order_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" bigint NOT NULL,
  "order_date" timestamp NOT NULL DEFAULT (now()),
  "order_status" order_status NOT NULL DEFAULT 'pending',
  "subtotal" decimal(12,2) NOT NULL CHECK (subtotal >= 0) DEFAULT 0,
  "tax_amount" decimal(12,2) NOT NULL CHECK (tax_amount >= 0) DEFAULT 0,
  "discount_amount" decimal(12,2) NOT NULL CHECK (discount_amount >= 0) DEFAULT 0,
  "total_amount" decimal(12,2) NOT NULL CHECK (total_amount >= 0),
  "currency" varchar(3) NOT NULL DEFAULT 'USD',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT "chk_order_total" CHECK (total_amount = subtotal + tax_amount - discount_amount)
);

CREATE TABLE "order_item" (
  "order_item_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "track_id" bigint,
  "album_id" bigint,
  "unit_price" decimal(10,2) NOT NULL CHECK (unit_price >= 0),
  "quantity" smallint NOT NULL CHECK (quantity > 0) DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT "chk_order_item_product" CHECK ((track_id IS NOT NULL AND album_id IS NULL) OR (track_id IS NULL AND album_id IS NOT NULL))
);

CREATE TABLE "payment" (
  "payment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "payment_date" timestamp NOT NULL DEFAULT (now()),
  "amount" decimal(12,2) NOT NULL CHECK (amount > 0),
  "payment_status" payment_status NOT NULL DEFAULT 'pending',
  "payment_mode" payment_mode NOT NULL,
  "transaction_reference" varchar(150) UNIQUE,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX "uq_customer_email" ON "customer" ("email");

CREATE INDEX "idx_customer_status" ON "customer" ("status");

CREATE INDEX "idx_artist_name" ON "artist" ("artist_name");

CREATE INDEX "idx_artist_status" ON "artist" ("status");

CREATE INDEX "idx_album_title" ON "album" ("album_title");

CREATE INDEX "idx_album_release_date" ON "album" ("release_date");

CREATE INDEX "idx_album_type" ON "album" ("album_type");

CREATE INDEX "idx_album_artist_artist" ON "album_artist" ("artist_id");

CREATE INDEX "idx_track_album" ON "track" ("album_id");

CREATE INDEX "idx_track_media_type" ON "track" ("media_type_id");

CREATE INDEX "idx_track_name" ON "track" ("track_name");

CREATE UNIQUE INDEX "uq_album_disc_track_number" ON "track" ("album_id", "disc_number", "track_number");

CREATE INDEX "idx_track_genre_genre" ON "track_genre" ("genre_id");

CREATE INDEX "idx_track_artist_artist" ON "track_artist" ("artist_id");

CREATE INDEX "idx_playlist_customer" ON "playlist" ("customer_id");

CREATE UNIQUE INDEX "uq_customer_playlist_name" ON "playlist" ("customer_id", "playlist_name");

CREATE UNIQUE INDEX "uq_playlist_track_position" ON "playlist_track" ("playlist_id", "track_position");

CREATE INDEX "idx_playlist_track_track" ON "playlist_track" ("track_id");

CREATE INDEX "idx_orders_customer" ON "orders" ("customer_id");

CREATE INDEX "idx_orders_date" ON "orders" ("order_date");

CREATE INDEX "idx_orders_status" ON "orders" ("order_status");

CREATE INDEX "idx_order_item_order" ON "order_item" ("order_id");

CREATE INDEX "idx_order_item_track" ON "order_item" ("track_id");

CREATE INDEX "idx_order_item_album" ON "order_item" ("album_id");

CREATE INDEX "idx_payment_order" ON "payment" ("order_id");

CREATE INDEX "idx_payment_status" ON "payment" ("payment_status");

CREATE INDEX "idx_payment_date" ON "payment" ("payment_date");

COMMENT ON COLUMN "customer"."updated_at" IS 'Update through application logic or a database trigger';

COMMENT ON COLUMN "artist"."updated_at" IS 'Update through application logic or a database trigger';

COMMENT ON COLUMN "album"."updated_at" IS 'Update through application logic or a database trigger';

COMMENT ON COLUMN "track"."updated_at" IS 'Update through application logic or a database trigger';

COMMENT ON COLUMN "playlist"."updated_at" IS 'Update through application logic or a database trigger';

COMMENT ON COLUMN "orders"."updated_at" IS 'Update through application logic or a database trigger';

COMMENT ON COLUMN "payment"."updated_at" IS 'Update through application logic or a database trigger';

ALTER TABLE "album_artist" ADD CONSTRAINT "fk_album_artist_album" FOREIGN KEY ("album_id") REFERENCES "album" ("album_id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "album_artist" ADD CONSTRAINT "fk_album_artist_artist" FOREIGN KEY ("artist_id") REFERENCES "artist" ("artist_id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "track" ADD CONSTRAINT "fk_track_album" FOREIGN KEY ("album_id") REFERENCES "album" ("album_id") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "track" ADD CONSTRAINT "fk_track_media_type" FOREIGN KEY ("media_type_id") REFERENCES "media_type" ("media_type_id") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "track_genre" ADD CONSTRAINT "fk_track_genre_track" FOREIGN KEY ("track_id") REFERENCES "track" ("track_id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "track_genre" ADD CONSTRAINT "fk_track_genre_genre" FOREIGN KEY ("genre_id") REFERENCES "genre" ("genre_id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "track_artist" ADD CONSTRAINT "fk_track_artist_track" FOREIGN KEY ("track_id") REFERENCES "track" ("track_id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "track_artist" ADD CONSTRAINT "fk_track_artist_artist" FOREIGN KEY ("artist_id") REFERENCES "artist" ("artist_id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "playlist" ADD CONSTRAINT "fk_playlist_customer" FOREIGN KEY ("customer_id") REFERENCES "customer" ("customer_id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "playlist_track" ADD CONSTRAINT "fk_playlist_track_playlist" FOREIGN KEY ("playlist_id") REFERENCES "playlist" ("playlist_id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "playlist_track" ADD CONSTRAINT "fk_playlist_track_track" FOREIGN KEY ("track_id") REFERENCES "track" ("track_id") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_customer" FOREIGN KEY ("customer_id") REFERENCES "customer" ("customer_id") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_item" ADD CONSTRAINT "fk_order_item_order" FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_item" ADD CONSTRAINT "fk_order_item_track" FOREIGN KEY ("track_id") REFERENCES "track" ("track_id") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_item" ADD CONSTRAINT "fk_order_item_album" FOREIGN KEY ("album_id") REFERENCES "album" ("album_id") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payment" ADD CONSTRAINT "fk_payment_order" FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
