BEGIN;

CREATE TYPE customer_status AS ENUM ('active', 'inactive', 'blocked');
CREATE TYPE artist_status AS ENUM ('active', 'inactive', 'retired');
CREATE TYPE album_type AS ENUM ('album', 'ep', 'single', 'compilation');
CREATE TYPE album_artist_role AS ENUM ('primary', 'featured', 'compilation');
CREATE TYPE track_artist_role AS ENUM ('primary', 'featured', 'composer', 'performer', 'producer');
CREATE TYPE playlist_visibility AS ENUM ('private', 'public', 'unlisted');
CREATE TYPE order_status AS ENUM ('pending', 'confirmed', 'completed', 'cancelled', 'refunded');
CREATE TYPE payment_status AS ENUM ('pending', 'successful', 'failed', 'refunded');
CREATE TYPE payment_mode AS ENUM ('card', 'upi', 'net_banking', 'wallet', 'paypal');

CREATE TABLE customer (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_no VARCHAR(30),
    city VARCHAR(100),
    country VARCHAR(100),
    registration_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status customer_status NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_customer_email CHECK (POSITION('@' IN email) > 1)
);

CREATE TABLE artist (
    artist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_name VARCHAR(255) NOT NULL,
    biography TEXT,
    website_url VARCHAR(500),
    debut_year SMALLINT CHECK (debut_year BETWEEN 1800 AND 2200),
    country VARCHAR(100),
    status artist_status NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE album (
    album_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_title VARCHAR(255) NOT NULL,
    release_date DATE,
    album_type album_type NOT NULL,
    album_price NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (album_price >= 0),
    cover_image_url VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE album_artist (
    album_id BIGINT NOT NULL,
    artist_id BIGINT NOT NULL,
    artist_role album_artist_role NOT NULL DEFAULT 'primary',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (album_id, artist_id, artist_role)
);

CREATE TABLE genre (
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE media_type (
    media_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_type_name VARCHAR(100) NOT NULL UNIQUE,
    file_extension VARCHAR(20),
    mime_type VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE track (
    track_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id BIGINT NOT NULL,
    media_type_id BIGINT NOT NULL,
    track_name VARCHAR(255) NOT NULL,
    duration_ms INTEGER NOT NULL CHECK (duration_ms > 0),
    unit_price NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
    is_explicit BOOLEAN NOT NULL DEFAULT FALSE,
    track_number SMALLINT NOT NULL CHECK (track_number > 0),
    disc_number SMALLINT NOT NULL DEFAULT 1 CHECK (disc_number > 0),
    release_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE track_genre (
    track_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (track_id, genre_id)
);

CREATE TABLE track_artist (
    track_id BIGINT NOT NULL,
    artist_id BIGINT NOT NULL,
    artist_role track_artist_role NOT NULL DEFAULT 'primary',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (track_id, artist_id, artist_role)
);

CREATE TABLE playlist (
    playlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    playlist_name VARCHAR(255) NOT NULL,
    playlist_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    playlist_visibility playlist_visibility NOT NULL DEFAULT 'private',
    description TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE playlist_track (
    playlist_id BIGINT NOT NULL,
    track_id BIGINT NOT NULL,
    track_position INTEGER NOT NULL CHECK (track_position > 0),
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (playlist_id, track_id),
    CONSTRAINT uq_playlist_track_position UNIQUE (playlist_id, track_position)
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    order_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    order_status order_status NOT NULL DEFAULT 'pending',
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    total_amount NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_order_total CHECK (total_amount = subtotal + tax_amount - discount_amount),
    CONSTRAINT chk_currency_format CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE TABLE order_item (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    track_id BIGINT,
    album_id BIGINT,
    unit_price NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
    quantity SMALLINT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    line_amount NUMERIC(12,2) GENERATED ALWAYS AS (unit_price * quantity) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_order_item_product CHECK (
        (track_id IS NOT NULL AND album_id IS NULL)
        OR
        (track_id IS NULL AND album_id IS NOT NULL)
    )
);

CREATE TABLE payment (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    payment_status payment_status NOT NULL DEFAULT 'pending',
    payment_mode payment_mode NOT NULL,
    transaction_reference VARCHAR(150) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE album_artist
    ADD CONSTRAINT fk_album_artist_album FOREIGN KEY (album_id)
    REFERENCES album (album_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE album_artist
    ADD CONSTRAINT fk_album_artist_artist FOREIGN KEY (artist_id)
    REFERENCES artist (artist_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE track
    ADD CONSTRAINT fk_track_album FOREIGN KEY (album_id)
    REFERENCES album (album_id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE track
    ADD CONSTRAINT fk_track_media_type FOREIGN KEY (media_type_id)
    REFERENCES media_type (media_type_id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE track_genre
    ADD CONSTRAINT fk_track_genre_track FOREIGN KEY (track_id)
    REFERENCES track (track_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE track_genre
    ADD CONSTRAINT fk_track_genre_genre FOREIGN KEY (genre_id)
    REFERENCES genre (genre_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE track_artist
    ADD CONSTRAINT fk_track_artist_track FOREIGN KEY (track_id)
    REFERENCES track (track_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE track_artist
    ADD CONSTRAINT fk_track_artist_artist FOREIGN KEY (artist_id)
    REFERENCES artist (artist_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE playlist
    ADD CONSTRAINT fk_playlist_customer FOREIGN KEY (customer_id)
    REFERENCES customer (customer_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE playlist_track
    ADD CONSTRAINT fk_playlist_track_playlist FOREIGN KEY (playlist_id)
    REFERENCES playlist (playlist_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE playlist_track
    ADD CONSTRAINT fk_playlist_track_track FOREIGN KEY (track_id)
    REFERENCES track (track_id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE orders
    ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id)
    REFERENCES customer (customer_id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE order_item
    ADD CONSTRAINT fk_order_item_order FOREIGN KEY (order_id)
    REFERENCES orders (order_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE order_item
    ADD CONSTRAINT fk_order_item_track FOREIGN KEY (track_id)
    REFERENCES track (track_id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE order_item
    ADD CONSTRAINT fk_order_item_album FOREIGN KEY (album_id)
    REFERENCES album (album_id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE payment
    ADD CONSTRAINT fk_payment_order FOREIGN KEY (order_id)
    REFERENCES orders (order_id) ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE INDEX idx_customer_status ON customer (status);
CREATE INDEX idx_customer_updated_at ON customer (updated_at);
CREATE INDEX idx_artist_name ON artist (artist_name);
CREATE INDEX idx_artist_updated_at ON artist (updated_at);
CREATE INDEX idx_album_release_date ON album (release_date);
CREATE INDEX idx_album_updated_at ON album (updated_at);
CREATE INDEX idx_album_artist_artist ON album_artist (artist_id);
CREATE INDEX idx_track_album ON track (album_id);
CREATE INDEX idx_track_media_type ON track (media_type_id);
CREATE INDEX idx_track_name ON track (track_name);
CREATE INDEX idx_track_updated_at ON track (updated_at);
CREATE UNIQUE INDEX uq_album_disc_track_number ON track (album_id, disc_number, track_number);
CREATE INDEX idx_track_genre_genre ON track_genre (genre_id);
CREATE INDEX idx_track_artist_artist ON track_artist (artist_id);
CREATE INDEX idx_playlist_customer ON playlist (customer_id);
CREATE UNIQUE INDEX uq_customer_playlist_name ON playlist (customer_id, playlist_name);
CREATE INDEX idx_playlist_track_track ON playlist_track (track_id);
CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE INDEX idx_orders_date ON orders (order_date);
CREATE INDEX idx_orders_status ON orders (order_status);
CREATE INDEX idx_orders_updated_at ON orders (updated_at);
CREATE INDEX idx_order_item_order ON order_item (order_id);
CREATE INDEX idx_order_item_track ON order_item (track_id);
CREATE INDEX idx_order_item_album ON order_item (album_id);
CREATE INDEX idx_order_item_updated_at ON order_item (updated_at);
CREATE INDEX idx_payment_order ON payment (order_id);
CREATE INDEX idx_payment_status ON payment (payment_status);
CREATE INDEX idx_payment_date ON payment (payment_date);
CREATE INDEX idx_payment_updated_at ON payment (updated_at);

COMMIT;
